/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface HolaBase {}
  interface HolaBaseAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'HolaBase': Components.HolaBase;
  }

  interface StencilIntrinsicElements {
    'hola-base': Components.HolaBaseAttributes;
  }


  interface HTMLHolaBaseElement extends Components.HolaBase, HTMLStencilElement {}
  var HTMLHolaBaseElement: {
    prototype: HTMLHolaBaseElement;
    new (): HTMLHolaBaseElement;
  };

  interface HTMLElementTagNameMap {
    'hola-base': HTMLHolaBaseElement
  }

  interface ElementTagNameMap {
    'hola-base': HTMLHolaBaseElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
