/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface HolaBase {}
  interface HolaBaseAttributes extends StencilHTMLAttributes {}

  interface HolaButton {
    'href': string;
    'submit': boolean;
    'type': string;
  }
  interface HolaButtonAttributes extends StencilHTMLAttributes {
    'href'?: string;
    'submit'?: boolean;
    'type'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'HolaBase': Components.HolaBase;
    'HolaButton': Components.HolaButton;
  }

  interface StencilIntrinsicElements {
    'hola-base': Components.HolaBaseAttributes;
    'hola-button': Components.HolaButtonAttributes;
  }


  interface HTMLHolaBaseElement extends Components.HolaBase, HTMLStencilElement {}
  var HTMLHolaBaseElement: {
    prototype: HTMLHolaBaseElement;
    new (): HTMLHolaBaseElement;
  };

  interface HTMLHolaButtonElement extends Components.HolaButton, HTMLStencilElement {}
  var HTMLHolaButtonElement: {
    prototype: HTMLHolaButtonElement;
    new (): HTMLHolaButtonElement;
  };

  interface HTMLElementTagNameMap {
    'hola-base': HTMLHolaBaseElement
    'hola-button': HTMLHolaButtonElement
  }

  interface ElementTagNameMap {
    'hola-base': HTMLHolaBaseElement;
    'hola-button': HTMLHolaButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
